FROM ubuntu:latest
#RUN apt update \
#  && apt install -y wget gcc g++ cmake make 
#  && wget https://github.com/HardySimpson/zlog/archive/1.2.12.tar.gz \
#  && tar xvf 1.2.12.tar.gz -C /usr/src/ \
#  && sed -i "s/-Werror//g" /usr/src/zlog-1.2.12/src/makefile \
#  && make -C /usr/src/zlog-1.2.12 \
#  && make -C /usr/src/zlog-1.2.12 install

ENV LD_LIBRARY_PATH=/usr/local/lib
